# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: dotnet-build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            7.0.x
          include-prerelease: false

      - name: Add to GitHub Repo
        run: |
          dotnet nuget add source --username Dynesshely --password ${{ secrets.GITHUBTOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Dynesshely/index.json"

      - name: Restore Dependencies for Csharpell.Core
        working-directory: Csharpell.Core
        run: dotnet restore

      - name: Build Csharpell.Core
        working-directory: Csharpell.Core
        run: dotnet build -c Release --no-restore
        
      - name: Restore Dependencies for Csharpell
        working-directory: Csharpell
        run: dotnet restore

      - name: Build Csharpell
        working-directory: Csharpell
        run: dotnet build -c Release --no-restore

      - name: Publish Csharpell.Core
        working-directory: Csharpell.Core
        run: |
          dotnet nuget push "./bin/Release/*.nupkg" --api-key ${{ secrets.NUGETKEY }} --source "https://api.nuget.org/v3/index.json" --skip-duplicate --no-symbols
          dotnet nuget push "./bin/Release/*.nupkg" --api-key ${{ secrets.GITHUBTOKEN }} --source "github" --skip-duplicate

      - name: Publish Csharpell
        working-directory: Csharpell
        run: |
          dotnet nuget push "./bin/Release/*.nupkg" --api-key ${{ secrets.NUGETKEY }} --source "https://api.nuget.org/v3/index.json" --skip-duplicate --no-symbols
          dotnet nuget push "./bin/Release/*.nupkg" --api-key ${{ secrets.GITHUBTOKEN }} --source "github" --skip-duplicate

#       - name: Test
#         run: dotnet test --no-build --verbosity normal
