# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: dotnet-build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            7.0.x
          include-prerelease: false

      - name: Add to GitHub Repo
        run: |
          nuget sources add -name github -Source https://nuget.pkg.github.com/Dynesshely/index.json -Username Dynesshely -Password ${{ secrets.GitHubToken }}

      - name: Install NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: '6.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore
        
      - name: Publish
        run: |
          nuget push ./bin/Release/*.nupkg -Source https://api.nuget.org/v3/index.json -SkipDuplicate -ApiKey ${{ secrets.NugetKey }} -NoSymbol
          nuget push ./bin/Release/*.nupkg -Source github -SkipDuplicate
      
#       - name: Test
#         run: dotnet test --no-build --verbosity normal
